node {
    stage ("Checkout DataService"){
        git branch: 'main', url: 'https://github.com/foxwas/bah-test-project.git'
    }
    
    stage ("Gradle Build - DataService") {
	
        sh '-b testproject/build.gradle gradle clean build'

    }
    
    stage ("Gradle Bootjar-Package - DataService") {
        sh '-b testproject/build.gradle gradle bootjar'
    }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {

	    stage('Release- DataService') {
	     sh '-b testproject/build.gradle gradle build -x test'
	     sh 'echo DataService is ready to release!'

	    }
	  }
    }
}
